--[[
************************************************************************
esES.lua
esES localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 7.0.3.2
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/esES/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "esES", false)

if not L then return end

L["ACQUIRETOOLTIPPOSITION_DESC"] = "Cambia la ubicación de la ventana que contiene la información para adquirir."
L["Acquisition"] = "Adquisición"
L["ACQUISITION_DESC_FORMAT"] = "Se mostrarán %s recolectables."
L["Aeonaxx"] = true
L["Aldraan"] = true
L["ALL_EXCLUDED"] = "Aunque haya escaneado esta colección, sus exclusiones impiden que se muestren. Por favor, cambie las exclusiones e inténtelo de nuevo"
L["ALL_FILTERED"] = "Tus filtros están impidiendo que las entradas se muestren. Por favor cambia la configuración de los filtros y vuelve a intentarlo."
L["ALL_KNOWN"] = "Conoce todos los recolectables de esta colección. Felicitaciones por su logro!"
L["ALT_CLICK"] = "Alt-Click para agregar/quitar esta montura/mascota de tu lista de ignorados."
L["Apothecary Furrows"] = "Boticario Furrows"
L["Apothecary Hummel"] = "Boticario Hummel"
L["Astrid Langstrump"] = true
L["Ayla Shadowstorm"] = "Ayla Ventiscaumbría"
L["Bana Wildmane"] = "Bana Ferocrín"
L["Baradin Fox"] = "Zorro de Baradin"
L["Belbi Quikswitch"] = "Belbi Tiratrastos"
L["Binding"] = "Ligado"
L["Blacksmith Abasi"] = "Herrero Abasi"
L["Blix Fixwidget"] = "Blix Chirimbolo"
L["BOA_DESC"] = "Monturas/Mascotas que son objetos Ligados a la Cuenta serán incluidos en el análisis."
L["BOAFilter"] = "Ligado a la Cuenta"
L["BOE_DESC"] = "Monturas/Mascotas que son objetos Ligados al Equipar serán incluidos en el análisis."
L["BOEFilter"] = "Ligado al Equipar"
L["Bogflare Needler"] = "Aguja cienagosa"
L["BOP_DESC"] = "Monturas/Mascotas que son objetos Ligados al Recoger serán incluidos en el análisis."
L["BOPFilter"] = "Ligado al Recogerlo"
L["Bottom Left"] = "Botón izquierdo"
L["Bottom Right"] = "Botón derecho"
L["Breanni"] = true
L["Briarthorn"] = "Brezospina"
L["Brunn Flamebeard"] = "Brunn Barballamas"
L["Challenger Soong"] = "Contendiente Soong"
L["Challenger Wuli"] = "Contendiente Wuli"
L["Chub"] = true
L["Cielstrasza"] = true
L["Clear Exclusion List"] = "Limpiar Lista de Exclusión"
L["CLEAR_EXCLUSION_LIST_DESC"] = "Elimina todas las entradas de la lista de exclusión."
L["Clockwork Assistant"] = "Ayudante robot cohete de cuerda"
L["CLOSE_DESC"] = "Cierre la ventana de Collectinator."
L["Close GUI"] = "Cerrar con una interfaz de usuario PetJournal"
L["CLOSEGUI_DESC"] = "Cierre la ventana Collectinator al cerrar la ventana PetJournal."
L["CONTRACTALL_DESC"] = "Minimiza todas las entradas que figuran a continuación."
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Cabo Arthur Flew"
L["CTRL_CLICK"] = "Ctrl-Click para añadir el enlace de esta entrada en tu chat."
L["CTRL_SHIFT_CLICK"] = "Ctrl-Shift-Click para añadir el objeto en el mapa y mini-mapa."
L["Dama Wildmane"] = "Dama Ferocrín"
L["Dame Evniki Kapsalis"] = "Dama Evniki Kapsalis"
L["Darahir"] = true
L["Darkmoon Rabbit"] = "Conejo de la Luna Negra"
L["Day of the Dead"] = "Día de los muertos"
L["Dealer Rashaad"] = "Tratante Rashaad"
L["Defias Pirate"] = "Pirata Defias"
L["Demisette Cloyce"] = true
L["Derrick Brindlebeard"] = "Derrick Barba Berrenda"
L["Deviate Guardian"] = "Guardián descarriado"
L["Deviate Ravager"] = "Devastador descarriado"
L["Dhugru Gorelust"] = "Dhugru Ansiagore"
L["DISPLAY_EXCLUSION_DESC"] = "Mostrar las entradas que están en la lista de exclusión."
L["Display Exclusions"] = "Mostrar Exclusiones"
L["DISPLAY_OPTIONS_DESC"] = "Te permite personalizar como la GUI se comporta."
L["Donni Anthania"] = true
L["Dormus the Camel-Hoarder"] = "Dormus el Acaparacamellos"
L["Dorothy"] = true
L["Doru Thunderhorn"] = "Doru Tronacuerno"
L["Drake Dealer Hurlunk"] = "Tratante de dracos Hurlunk"
L["Dread Commander Thalanor"] = "Comandante aterrador Thalanor"
L["Driz Tumblequick"] = "Driz Pataplaf"
L["Durgan Thunderbeak"] = "Durgan Truenopico"
L["Eliza Killian"] = true
L["EXCLUDECOUNT_DESC"] = "Incluir entradas excluidas en el número de entradas totales."
L["EXPANDALL_DESC"] = "Expandir todas las entradas que figuran a continuación."
L["EXPANSION_DESC_FORMAT"] = "Mostrar recolectados liberados en %s"
L["EXPANSION_FILTER_FORMAT"] = "Mostrar una selección de %s reputaciones a incluir en el escaneo."
L["FACTION_DESC_FORMAT"] = "Incluir recolectables que tienen que ser obtenidos por %s jugadores."
L["Fedryen Swiftspear"] = "Fedryen Lanza Presta"
L["FILTER_CLOSE_DESC"] = "Cerrar panel de filtros."
L["FILTERCOUNT_DESC"] = "Tratar los elementos filtrados como inexistentes. Al seleccionar esta opción cambiará el número de objetos coleccionables conocidos y desconocidos."
L["FILTER_DESC_FORMAT"] = "Alterna la visualización de %s coleccionables."
L["FILTERING_BINDING_DESC"] = "Configuración de que tipos de ligados están incluidos en el análisis."
L["FILTERING_GENERAL_DESC"] = "Configuración para varios tipos generales de filtros."
L["FILTERING_ITEM_DESC"] = "Configuración de los elementos incluidos en el análisis."
L["FILTERING_MISC_DESC"] = "Configuración de opciones varias que también están presentes en las opciones de visualización."
L["FILTERING_OBTAIN_DESC"] = "Configuración de los métodos de obtención que están incluidos en el análisis."
L["FILTERING_QUALITY_DESC"] = "Configuración por calidades a incluir en el escaneo."
L["FILTERING_REP_DESC"] = "Configurar las recompensas de reputación incluidas en el análisis."
L["FILTER_OPEN_DESC"] = "Abrir panel de filtros.."
L["Flik"] = true
L["FONT_SIZE_DESC"] = "Cambiar el tamaño de las fuentes."
L["Freka Bloodaxe"] = "Freka Hacha de Sangre"
L["Gaelden Hammersmith"] = "Gaelden Martillero"
L["Geen"] = true
L["Gregor MacVince"] = true
L["Grella"] = "Grella "
L["Grol'dar"] = true
L["GROUP_TOGGLE_FORMAT"] = "Click-izq para seleccionar o Click-dcho para deseleccionar todos %s filtros."
L["Grunda Bronzewing"] = "Grunda Alabronce"
L["Grunnda Wolfheart"] = "Grunnda Corazón de Lobo"
L["Gundrak Raptor"] = "Raptor de Grundrak"
L["Halpa"] = true
L["Harb Clawhoof"] = "Harb Garrapezuña"
L["Hide Pop-Up"] = "Ocultar Pop-Up"
L["HIDEPOPUP_DESC"] = [=[Evita los pop-ups que notifican porque la ventana de análisis está vacia. Los Pop-ups siempre se mostrarán la primera vez después de haber instalado una nueva versión.
]=]
L["Hiren Loresong"] = "Hiren Romanza"
L["Include Excluded"] = "Incluir Excluidos"
L["Include Filtered"] = "Incluir Filtrados"
L["Irisee"] = true
L["Jadefang"] = "Colmillo de Jade"
L["Jepetto Joybuzz"] = "Jepetto Jugarreta"
L["Jeremiah Payson"] = true
L["Jilanne"] = true
L["Kall Worthaton"] = "Kall Valemil"
L["Katie Hunter"] = "Katie Cazadora"
L["Knight Dameron"] = "Caballero Dameron"
L["Known"] = "Conocido"
L["KNOWN_DESC"] = "Incluir todos los coleccionables conocidos en el análisis."
L["Larkin Thunderbrew"] = "Larkin Cebatruenos"
L["Lelanai"] = true
L["Lhara"] = true
L["Lieutenant Karter"] = "Teniente Karter"
L["Lillehoff"] = true
L["Lil Timmy"] = "Pequeño Timmy"
L["Location"] = "Localización"
L["Main Filter Options"] = "Opciones de filtro generales"
L["MAINFILTER_OPTIONS_DESC"] = "Te permite especificar cuantos filtros diferentes son gestionados."
L["Main Options"] = "Opciones generales"
L["MAIN_OPTIONS_DESC"] = "Opciones de configuración principal"
L["Maximillian Crowe"] = true
L["Mei Francis"] = true
L["Michelle De Rum"] = "Michelle De Ron"
L["Midsummer Merchant"] = "Mercader del solsticio de verano"
L["Midsummer Supplier"] = true
L["Milli Featherwhistle"] = "Milli Plumasilba"
L["Mirket"] = true
L["Miscellaneous"] = "Miscelánea"
L["Mob Drop"] = true
L["Mycah"] = true
L["Narkk"] = true
L["Noblegarden Merchant"] = true
L["Noblegarden Vendor"] = true
L["NO_DISPLAY"] = "No hay entradas para mostrar. Si recibes este mensaje por favor envía un ticket a http://www.wowace.com/projects/collectinator/tickets describiendo los filtros que tienes, tu lista de exclusión, que tipo de análisis realizabas, y el número de entradas conocidas/desconocidas."
L["NoItemLink"] = "Este objeto parece no tener un enlace de objeto o no está en tu caché."
L["NOTSCANNED"] = "No has analizado este coleccionable. Por favor abre la interfaz y haz clic en análisis. Recuerda que el análisis de monturas/mascotas se realiza al mismo tiempo."
L["NOT_YET_SCANNED"] = "Todavía no ha sido analizado!"
L["Noxious Whelp"] = "Cría nociva"
L["Obtained From"] = "Obtenido de"
L["Ogunaro Wolfrunner"] = "Ogunaro Correlobo"
L["\"Plucky\" Johnson"] = "\"Desplumado\" Johnson"
L["Pogg"] = true
L["Pol Amberstill"] = "Pol Semperámbar"
L["Poseidus"] = true
L["Profile Options"] = "Opciones de perfil"
L["Provisioner Nasela"] = "Proveedora Nasela"
L["Quartermaster Brazie"] = "Intendente Brazie"
L["Raider Bork"] = "Asaltante Bork"
L["Ray'ma"] = true
L["RESET_DESC"] = "Reiniciar todos los filtros a sus valores por defecto"
L["RESET_WINDOW_DESC"] = "Reinicia la GUI a su posición por defecto."
L["Reset Window Position"] = "Reiniciar posición de ventana"
L["Retired"] = "Retirado"
L["Richard Kerwin"] = true
L["Rillie Spindlenut"] = "Rillie Ejeloco"
L["Rook Hawkfist"] = "Rook Puñohalcón"
L["Rupert Boch"] = true
L["Sairuk"] = true
L["Samamba"] = true
L["Sandahl"] = true
L["Scalding Whelp"] = "Cría hirviente"
L["Scan"] = "Análisis"
L["Scan Button Position"] = "Posición del botón de escaneo"
L["SCANBUTTONPOSITION_DESC"] = [=[Permite personalizar donde colocar el botón de escaneo en el marco de Monturas y Mascotas .
]=]
L["SCAN_COMPANIONS_DESC"] = "Análizar la ventana actual abierta de compañeros."
L["SEARCH_FILTERED"] = "Tu búsqueda carece de resultados"
L["Searing Whelp"] = "Cría abrasadora"
L["SHIFT_CLICK"] = "Mayus-click para añadir el objeto creado por este coleccionable a tu chat."
L["Shylenai"] = true
L["Sixx"] = true
L["SORTING_DESC"] = "Cambiar la forma en que coleccionables mostrados son clasificados."
L["SPECIFIC_REP_DESC"] = "Incluir %s facción."
L["SPELLTOOLTIPPOSITION_DESC"] = "Cambiar la localizacion de la nota que contiene la información del coleccionable."
L["Stone Guard Mukar"] = "Guardia de piedra Mutaha"
L["Strahad Farsan"] = true
L["Tanaika"] = true
L["Tanak"] = true
L["TCG"] = "WoW Trading Card Game"
L["Terokk"] = true
L["Thanthaldis Snowgleam"] = "Thanthaldis Brillaneve"
L["Thistleheart"] = "Corazón de Cardo"
L["Time-Lost Proto Drake"] = "Protodraco Tiempo Perdido"
L["Tohfo Skyhoof"] = "Tohfo Pezuñacielo"
L["Tooltip (Acquire) Position"] = "Nota (Adquirir) Posición"
L["Tooltip Options"] = "Opciones de nota"
L["TOOLTIP_OPTIONS_DESC"] = "Te permite especificar como se comportan las notas. La notas de adquisición muestran la información de como adquirir el coleccionable, mientras que la nota de habilidad muestra la informacion del propio coleccionable."
L["Tooltip Scale"] = "Tamaño de nota"
L["TOOLTIP_SCALE_DESC"] = "Cambia la escala de la nota. El rango va desde .5 hasta 1.5 (.9 por defecto)"
L["Top Left"] = "Arriba a la izquierda"
L["Top Right"] = "Arriba a la derecha"
L["Torallius the Pack Handler"] = "Torallius el Controlador de la Manada"
L["Trader Narasu"] = "Comerciante Narasu"
L["Trainer"] = "Instructor"
L["Trellis Morningsun"] = "Trellis Sol de Mañana"
L["UI_SCALE_DESC"] = "Cambia la escala de la UI. El rango va desde .5 hasta 1.5 (1 por defecto)"
L["Unger Statforth"] = true
L["UNKNOWN_DESC"] = "Incluir todos los coleccionables desconocidos en el análisis."
L["Ursula Deline"] = true
L["Valadar Starsong"] = "Valadar Cantoestelar"
L["Varlan Highbough"] = "Varlan Ramaalta"
L["Vasarin Redmorn"] = "Vasarin Rojoalbor"
L["Veron Amberstill"] = "Veron Semperámbar"
L["View Exclusion List"] = "Ver lista de exclusión"
L["VIEW_EXCLUSION_LIST_DESC"] = "Imprime una lista de todas las entradas en la lista de exclusión."
L["Winaestra"] = true
L["World Drop"] = true
L["Xan'tish"] = true
L["Yarlyn Amberstill"] = "Yarlyn Semperámbar"
L["Zachariah Post"] = true
L["Zen'Vorka"] = true
L["Zevrost"] = true
L["Zjolnir"] = true
