--[[
************************************************************************
esMX.lua
esMX localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 7.0.3.2
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/esMX/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "esMX", false)

if not L then return end

L["Bana Wildmane"] = "Bana Ferocrín"
L["Belbi Quikswitch"] = "Belbi Tiratrastos"
L["Blix Fixwidget"] = "Blix Chirimbolo"
