--[[
************************************************************************
ptBR.lua
ptBR localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 7.0.3.2
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/ptBR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "ptBR", false)

if not L then return end

L["Aldraan"] = true
L["Bana Wildmane"] = "Bana Juba Agreste"
L["Belbi Quikswitch"] = "Bebel Trocarrápida"
L["Blix Fixwidget"] = "Blix Consertatreco"
L["Bogflare Needler"] = "Agulheiro Brejolume"
L["Breanni"] = true
L["Briarthorn"] = "Cravespinho"
L["Brunn Flamebeard"] = "Bruno Barbachama"
L["Cielstrasza"] = true
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Cabo Arthur Volus"
L["Dama Wildmane"] = "Dara Juba Agreste"
L["Dame Evniki Kapsalis"] = "Dama Evniki Kapsalis"
L["Darahir"] = true
L["Dealer Rashaad"] = "Mercador Rashaad"
L["Defias Pirate"] = "Pirata Défias"
L["Demisette Cloyce"] = "Joyce Lopes"
L["Derrick Brindlebeard"] = "Derico Barbalistra"
L["Deviate Guardian"] = "Guardião Anormal"
L["Deviate Ravager"] = "Assolador Anormal"
L["Dhugru Gorelust"] = "Dhugru Gostassangue"
L["Donni Anthania"] = "Cristiana Justa"
L["Doru Thunderhorn"] = "Doru Chifre Troante"
L["Drake Dealer Hurlunk"] = "Comerciante de Dracos Hurlunk"
L["Dread Commander Thalanor"] = "Terrível Comandante Thalanor"
L["Driz Tumblequick"] = "Driz Topalogo"
L["Durgan Thunderbeak"] = "Durgan Rostrovão"
L["Eliza Killian"] = "Elisa Morgado"
L["Fedryen Swiftspear"] = "Fedryen Lancélere"
L["Flik"] = true
L["Freka Bloodaxe"] = "Freiga Machado Sangrento"
L["Gaelden Hammersmith"] = "Gaelden Marteleiro"
L["Geen"] = true
L["Gregor MacVince"] = true
L["Grella"] = "Drella"
